Traceback (most recent call last):
  File "get_vibrations.py", line 848, in <module>
    main()
  File "get_vibrations.py", line 523, in main
    data=open(folder+'/'+filename)
IOError: [Errno 2] No such file or directory: 'MoS2.i_atom_28.i_coord_0.displ_0.002/aims.out'
